### ISSUE TITLE
Possibility to add a minimum score for a request

### ISSUE THREAD

**Issue by kevinmu17** [Simplon-Prod/craft-google-recaptcha#2]
The V3 library lets through much spam these days, complaints are all over the place. is there a way to implement a score with the rendered code?
[Recaptcha v3 docs](https://developers.google.com/recaptcha/docs/v3#actions)

A suggestion would be:
```twig
{{ craft.googleRecaptcha.render({ id: 'recaptcha-widget', score: 0.6 }) }}
```

**Comment by kevinmu17** [comment]
@juban I see you updated the plugin with these features. Could you add #2 to the release for this request and close this issue with the commit.

**Comment by juban** [comment]
@kevinmu17 
Yes, and I hope you will find the enhancements useful.
Feel free to give you feedback if you think there's a better approach.
I forgot to add a reference to that ticket, my bad. Will do.
